"""initial

Revision ID: ae512b977fc9
Revises: 
Create Date: 2026-02-07 21:20:45.750345

"""
from typing import Sequence, Union

import pgvector
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae512b977fc9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('belly_embedding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_name', sa.String(), nullable=False),
    sa.Column('newt_class_name', sa.String(), nullable=False),
    sa.Column('image_sha256', sa.String(length=64), nullable=False),
    sa.Column('image_bytes', sa.LargeBinary(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=256), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_sha256')
    )
    op.create_index('belly_embedding_hnsw_cosine_idx', 'belly_embedding', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('belly_embedding_newt_idx', 'belly_embedding', ['newt_class_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('belly_embedding_newt_idx', table_name='belly_embedding')
    op.drop_index('belly_embedding_hnsw_cosine_idx', table_name='belly_embedding', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('belly_embedding')
    # ### end Alembic commands ###
